import { AccHDP } from "../../types";

export const mockDataAcc: AccHDP[] = [
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
    {
        email: "testemail@test.com",
        password: "acjf3fsh",
        proxy: "172.208.193.35:31337:sOwgsdfj",
        status: "Login finish n1",
        data: "",
        group: "no_acc",
    },
];
